app:
  title: "Crawl4AI API"
  version: "1.0.0"

security:
  enabled: true
  jwt_enabled: true
  jwt_secret_key: "${JWT_SECRET_KEY}"
  jwt_algorithm: "HS256"
  jwt_expire_minutes: ${JWT_EXPIRE_MINUTES:-30}
  https_redirect: false
  trusted_hosts: ["*"]

rate_limiting:
  enabled: true
  default_limit: "${RATE_LIMIT}"
  trusted_proxies: []
  storage_uri: "memory://"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  ssl: false
  ssl_cert_reqs: null
  ssl_ca_certs: null
  ssl_certfile: null
  ssl_keyfile: null

# Crawler Configuration
crawler:
  base_config:
    simulate_user: true
  memory_threshold_percent: 95.0
  rate_limiter:
    enabled: true
    base_delay: [1.0, 2.0]
  timeouts:
    stream_init: 30.0
    batch_process: 300.0
  pool:
    max_pages: 40
    idle_ttl_sec: 1800
  browser:
    kwargs:
      headless: true
      text_mode: true

llm:
  provider: "${LLM_PROVIDER:-openai/gpt-4o-mini}"
  api_key_env: "${LLM_API_KEY_ENV:-OPENAI_API_KEY}"
  temperature: ${LLM_TEMPERATURE:-0.7}
  max_tokens: ${LLM_MAX_TOKENS:-2000}
  base_url: "${LLM_BASE_URL:-}"

logging:
  level: "${LOG_LEVEL:-INFO}"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

observability:
  prometheus:
    enabled: true
    endpoint: "/metrics"
  health_check:
    endpoint: "/health"